name: Prod Code Deploy
# This deploys code changes to prod from release artifacts already present in the shared CI bucket and ECR repository.

on:
  workflow_dispatch:
    inputs:
      lambda_version:
        description: "Lambda release tag to deploy e.g. 0.9.4"
        required: true
      ecs_version:
        description: "ECS release tag to deploy e.g. 0.9.4"
        required: true
      frontend_version:
        description: "Frontend release tag to deploy; defaults to lambda_version"
        required: false

permissions:
  id-token: write
  contents: write

jobs:
  get_build:
    name: Resolve
    uses: ./.github/workflows/shared_build_get.yml
    with:
      environment: ci
      lambda_version: ${{ inputs.lambda_version }}
      frontend_version: ${{ inputs.frontend_version }}
      ecs_version: ${{ inputs.ecs_version }}

  deploy:
    name: Deploy
    uses: ./.github/workflows/shared_deploy.yml
    needs:
      - get_build
    with:
      environment: prod
      lambda_version: ${{ needs.get_build.outputs.lambda_version }}
      ecs_version: ${{ needs.get_build.outputs.ecs_version }}
      code_bucket: ${{ needs.get_build.outputs.code_bucket }}
      ecr_repository_url: ${{ needs.get_build.outputs.ecr_repository_url }}
