name: Shared Infra Releases

on:
  workflow_call:
    inputs:
      environment:
        description: environment reference i.e. 'prod' or 'dev'
        required: true
        type: string
      infra_version:
        description: "Version of infrastructure (terraform) to be deployed"
        required: true
        type: string
    outputs:
      code_bucket:
        description: "Bucket containing build artifacts"
        value: ${{ jobs.bucket.outputs.bucket_name }}
      ecr_repository_url:
        description: "ECR repository url"
        value: ${{ jobs.ecr.outputs.ecr_repository_url }}

concurrency: # only run one instance of workflow at any one time
  group: ${{ github.workflow }}-${{ inputs.environment }}
  cancel-in-progress: false

permissions:
  id-token: write
  contents: write

env:
  AWS_OIDC_ROLE_ARN: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/${{ vars.PROJECT_NAME }}-${{ inputs.environment }}-github-oidc-role
  AWS_REGION: ${{ vars.AWS_REGION }}

jobs:
  ecr:
    name: ECR
    runs-on: ubuntu-latest
    outputs:
      ecr_repository_url: ${{ steps.get_ecr_repository_url.outputs.ecr_repository_url }}
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.infra_version }}

      - uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ env.AWS_OIDC_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy ECR
        id: deploy_ecr
        uses: ./.github/actions/terragrunt
        with:
          tg_directory: infra/live/${{ inputs.environment }}/aws/ecr

      - name: Get ECR repository url
        id: get_ecr_repository_url
        env:
          TG_OUTPUTS: ${{ steps.deploy_ecr.outputs.tg_outputs }}
        run: |
          echo "ecr_repository_url=$(echo "$TG_OUTPUTS" | jq -r '.repository_url.value')" >> "$GITHUB_OUTPUT"

  bucket:
    name: Code Bucket
    runs-on: ubuntu-latest
    outputs:
      bucket_name: ${{ steps.get_bucket_name.outputs.bucket }}
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.infra_version }}

      - uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ env.AWS_OIDC_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Read Lambda artifact dir
        id: lambda_artifact_dir
        uses: ./.github/actions/just
        with:
          justfile_path: justfile.ci
          just_action: code-bucket-get-lambda-artifact-dir

      - name: Read AppSpec artifact dir
        id: appspec_artifact_dir
        uses: ./.github/actions/just
        with:
          justfile_path: justfile.ci
          just_action: code-bucket-get-appspec-artifact-dir

      - name: Deploy build artifact bucket
        id: deploy_bucket
        uses: ./.github/actions/terragrunt
        env:
          TF_VAR_lambda_artifact_dir: ${{ steps.lambda_artifact_dir.outputs.just_outputs }}
          TF_VAR_appspec_artifact_dir: ${{ steps.appspec_artifact_dir.outputs.just_outputs }}
        with:
          tg_directory: infra/live/${{ inputs.environment }}/aws/code_bucket

      - name: Get bucket name
        id: get_bucket_name
        env:
          TG_OUTPUTS: ${{ steps.deploy_bucket.outputs.tg_outputs  }}
        run: |
          echo "bucket=$(echo $TG_OUTPUTS | jq -r '.bucket.value')" >> $GITHUB_OUTPUT
